name: SayiTahminOyunu CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: Python Kurulum
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Python sürümünü ayarlayın

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements file found."

      - name: Uygulamayı Çalıştır
        run: python Tahmin.py

      - name: Unit Testleri Çalıştır
        run: python -m unittest test_Tahmin.py
